telegram:
  token: ""
  timeout: 60

limits:
  - bucket: 5m
    limit: 1
  - bucket: 1h
    limit: 5
    
# Match syntax https://pkg.go.dev/regexp/syntax
trigger:
  - match: "WTF?"
    text: "What the Fish?"
  - match: "(?i)guten morgen"
    text: "Nimm Dir nen Kaffee! ☕️"
  - match: "[Dd]ie \\d+ Freunde"
    text: "... und Timmy der Hund"
