telegram:
  token: ""
  timeout: 60

# Match syntax https://pkg.go.dev/regexp/syntax
trigger:
  - match: "WTF?"
    text: "What the Fuck?"
  - match: "(?i)guten morgen"
    text: "Nimm Dir nen Kaffee! ☕️"
  - match: "[Dd]ie \\d+ Freunde"
    text: "... und Timmy der Hund"
