telegram:
  token: ""
  timeout: 60

# Match syntax https://pkg.go.dev/regexp/syntax
trigger:
  - match: "(?i)faultier"
    text: "Lass uns zusammen rumhängen!"
  - match: "(?i)guten morgen"
    text: "Lass mich weiterschlafen!"
  - match: "😡"
    text: "*Entspann dich mal, Digga!*"
  - match: "(?i)schlafen"
    text: "Schlafen ist mein Lebenssinn."
  - match: "😠"
    text: "Chill mal deine Basis!"
  - match: "(?)besuchen"
    text: "Ich kann dich schon sehen, bin übermorgen bei dir!"
  - match: "😴"
    text: "Ich sehe immer müde aus..."
  - match: "(?)wach"
    text: "Kaum wach, schon wieder müde..."
  - match: "Ast"
    text: "*EIN KÖNIGREICH FÜR EINEN AST*"
  - match: "(?)mach ich"
    text: "Mach ich morgen… in einem Jahr…"
  - match: "(?)schnell"
    text: "He! Nicht so schnell Schnecke!"
  - match: "Sex"
    text: "_GÄHN!_"
  - match: "(?)gähn|müde|schlaf|bett"
    text: "Ich bin auch müde 🥱"
  - match: "Hunger|Blatt"
    text: "*Hmmm.. Blätter*"
